name: Fakelake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release --verbose
    - name: Generate tests/all_options.yaml
      run: target/release/fakelake generate tests/all_options.yaml
